.github/workflows/pr.yaml, Makefile
Added a workflow for PRs. 
Updated the controller gen path to api only otherwise compiler look for [embedded files](https://github.com/cnoe-io/idpbuilder/blob/5e87a01dbebd81028d6f76eaf627b1d82010b3b6/pkg/controllers/crd.go#L19) that's not yet generated and fails.
```
make manifests
mkdir -p /home/ssm-user/t/bin
test -s /home/ssm-user/t/bin/controller-gen && /home/ssm-user/t/bin/controller-gen --version | grep -q v0.12.0 || \
GOBIN=/home/ssm-user/t/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.12.0
/home/ssm-user/t/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=pkg/controllers/resources
pkg/controllers/crd.go:19:12: pattern resources/*.yaml: no matching files found
Error: not all generators ran successfully
run …
```
=> add workflow for PR

pkg/apps/srv/backstage/install.yaml
Updated the backstage manifests to:
1. Use in-memory database
2. Setup cluster role and binding to work with the default backstage image
3. Make the kind cluster available as a target cluster in Backstage
fixes: #12
=> fix backstage manifests

pkg/apps/srv/crossplane/crossplane.yaml
- Issue: #42 
- Fix wrong argocd project name from idpbuilder-embedded-gitserver to idpbuilder-local-gitserver for Crossplane
```
ARGOCD_SERVER=argocd.idpbuilder.cnoe.io.localtest.me:8443
ARGOCD_USER=admin
ARGOCD_PWD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
argocd login --insecure $ARGOCD_SERVER --username $ARGOCD_USER --password $ARGOCD_PWD
'admin:login' logged in successfully
Context 'argocd.idpbuilder.cnoe.io.localtest.me:8443' updated
argocd app list
NAME                                             CLUSTER                         NAMESPACE          PROJECT                     STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                                                     PATH           TARGET …
```
=> Fix wrong argocd project name from idpbuilder-embedded-gitserver to idpbuilder-local-gitserver

.github/workflows/pr.yaml, .github/workflows/release.yaml, .goreleaser.yaml, Makefile
Added a release GH action. Not supporting Windows for now because I have tested in Linux and MacOS only. 
Example Action: https://github.com/nabuskey/idpbuilder/actions/runs/6619626640
Release created: https://github.com/nabuskey/idpbuilder/releases/tag/v0.0.1
closes: #50
=> add go releaser

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml
We will need to add PR, enhancements, and questions later.
=> add bug template

README.md, go.mod, pkg/apps/srv/nginx-ingress/ingress-nginx.yaml, pkg/build/build.go, pkg/cmd/create/root.go, pkg/kind/cluster.go, pkg/kind/cluster_test.go, pkg/kind/registry_test.go, pkg/kind/resources/kind.yaml
- Issue #54
- Remove non needed 2nd kubernetes node to deploy only the control plane
- Add 2 new parameters to allow to set the kube version and extraPortMappings
=> Remove non needed 2nd kubernetes node

pkg/apps/srv/crossplane/crossplane.yaml, pkg/cmd/create/root.go, pkg/controllers/localbuild/controller.go
fixes: #42 
As discussed in the issue above, we will use the default project for this release to ensure all embedded apps deploy.  I also fixed the default kind image tag.
```bash
kubectl get applications -n argocd -o custom-columns="NAME":.metadata.name,"PROJECT":.spec.project
NAME                                       PROJECT
crossplane-helm                            default
idpbuilder-local-gitserver-argocd          default
idpbuilder-local-gitserver-backstage       default
idpbuilder-local-gitserver-crossplane      default
idpbuilder-local-gitserver-nginx-ingress   default
```
=> use argocd default project

pkg/controllers/localbuild/argo_test.go
```bash
➜  cnoe/idpbuilder git:(fix/tests) ✗ yq ea '[.] | length' pkg/controllers/localbuild/resources/argo/install.yaml
55
➜  cnoe/idpbuilder git:(fix/tests) ✗ ls -lh pkg/controllers/localbuild/resources/argo/
total 2152
-rw-r--r--  1 mccloman  staff   1.0M Sep 29 10:06 install.yaml
```
So the number of resources should be 1 and the number of objects in the argocd resource file should be 55. 
We will need to make a bit more robust tests in the future but I want to fix these tests so that they don't show up as failures every PR.
=> fix argocd controller tests

pkg/controllers/gitserver/image_test.go, pkg/kind/registry_test.go
The test assume we have a docker network named "kind". Since the test only cares about registry image, we'll just create the network prior to reconciling. 
Note that we will not need this functionality going forward. If we did, I think the way @cmoulliard did with test containers is the way to go. I want to fix tests so we don't run into test failures for unrelated PRs. 
```bash
ubuntu@ip-10-192-11-119:~/idpbuilder$ go test github.com/cnoe-io/idpbuilder/pkg/kind -run '^\QTestReconcileRegistry\E$'
ok  	github.com/cnoe-io/idpbuilder/pkg/kind	4.495s
ubuntu@ip-10-192-11-119:~/idpbuilder$ docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
ubuntu@ip-10-192-11-119:~/idpbuilder$ docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
906d8469762b   bridge    bridge    local …
```
=> create kind network

Makefile, pkg/controllers/gitserver/image_test.go, pkg/kind/registry_test.go
We need to make sure go vet is run before merge.
=> run go vet

pkg/controllers/localbuild/installer.go
Instead of relying on install object's namespace, use the known namespace. 
Ran into an issue where the gitea deployment object was not found because the install manifest does not define a namespace. We know where deployment should go, so let's look in that namespace.
=> use known namespace

pkg/apps/resources.go, pkg/controllers/localbuild/argo_test.go, pkg/controllers/localbuild/resources/argo/ingress.yaml
Installing ArgoCD ingress with the rest of ArgoCD resources.
=> move ingress

pkg/build/build.go
We should handle the error returned by `CreateOrUpdate` to ensure the CLI does not hang indefinitely when error is returned. 
fixes: #94
=> handle localbuild creation error and look for cluster scoped object

pkg/controllers/run.go, pkg/kind/cluster.go
Currently the registry container is created and runs even though it is not used by anything. This PR prevents the git server controller from running and creating the registry container.
Part of: https://github.com/cnoe-io/idpbuilder/issues/80
=> prevent git server from running

pkg/docker/image.go
Without this, kind fails if the docker server version doesnt specifically match the one we link against. e.g. if running a slightly old docker server this fails.
=> enable docker client API version negotiation

pkg/build/build.go, pkg/cmd/create/root.go
Relates to https://github.com/cnoe-io/idpbuilder/issues/92
Makes it emit a series of log messages after the `idpbuilder create` command completes successfully. Gets the ArgoCD Password from K8s and logs the username/password and URL for ArgoCD.
Emits something like 
```
1.7024070614792352e+09  INFO    controller.custompackage        All workers finished    {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "CustomPackage"}
1.702407061479521e+09   INFO    Stopping and waiting for caches
1.702407061479584e+09   INFO    Stopping and waiting for webhooks
1.7024070614795892e+09  INFO    Wait completed, proceeding to shutdown the manager
########################### Finished Creating IDP Successfully! ############################
Can Access ArgoCD at …
```
=> Print Argo Information After Creation

api/v1alpha1/custom_package_types.go, pkg/build/build.go, pkg/cmd/create/root.go, pkg/cmd/gitserver/create/root.go, pkg/controllers/custompackage/controller.go, pkg/controllers/localbuild/controller.go, pkg/controllers/resources/idpbuilder.cnoe.io_custompackages.yaml, pkg/controllers/run.go
With this change, cli exits by default. To have it continuously sync, you must provide the new flag `--no-exit`. 
fixes: #107
=> add a flag to specify if the cli should exit once packages are synced

README.md, pkg/cmd/create/root.go, pkg/cmd/gitserver/create/root.go
I standardized all the CLI flags to kebab-case
[Closes #116 ]
=> Standardize CLI flags

CONTRIBUTING.md, api/v1alpha1/custom_package_types.go, pkg/controllers/gitrepository/controller.go, pkg/controllers/localbuild/gitea.go, pkg/controllers/localbuild/resources/gitea/k8s/install.yaml, pkg/controllers/localbuild/resources/gitea/values.yaml, pkg/controllers/resources/idpbuilder.cnoe.io_custompackages.yaml, pkg/kind/cluster_test.go, pkg/kind/resources/kind.yaml
- enable skipTLSVerify
- fix documentation
closes #113
=> fix: use https for gitea

pkg/controllers/custompackage/controller.go, pkg/controllers/custompackage/controller_test.go, pkg/controllers/custompackage/test/resources/customPackages/testDir/app2.yaml, pkg/controllers/custompackage/test/resources/customPackages/testDir/app2/one/busybox.yaml, pkg/controllers/custompackage/test/resources/customPackages/testDir/app2/two/busybox.yaml
Fixes an issue when you are using multi sources in ArgoCD, the repo url was not updated correctly. It was because we were not updating the correct object.
=> ensure multi source spec is handled

hack/ingress-nginx/deployment-ingress-nginx.yaml, hack/ingress-nginx/generate-manifests.sh, hack/ingress-nginx/kustomization.yaml, hack/ingress-nginx/service-ingress-nginx.yaml, pkg/controllers/localbuild/resources/nginx/k8s/ingress-nginx.yaml
This PR adds a script to generate ingress-nginx manifests.
It also adds an alternative internal https port (8443) for ingress-nginx. 
Reason for adding 8443 is that it allows us to support a bit more complex set up where in-cluster URI must match external URI exactly. 
For example, for OIDC endpoint discovery to work, the issuer URL given to clients must match what is returned by the OIDC broker. See below: 
1. Keycloak is installed and configured. Ingress is created, and the endpoint is available at `https://kyecloak.cnoe.localtest.me:8443` on my local machine. 
2. Now, I want to configure Argo Workflows to use the Keycloak instance as IdP. Normally, I specify the externally available keycloak issuer url such as `https://keycloak.cnoe.localtest.me:8443/realms/cnoe`.
3. Unfortunately, I …
=> generate ingress-nginx manifests

.goreleaser.yaml, Makefile, go.mod, go.sum, pkg/cmd/root.go, pkg/cmd/version/root.go
Adds a simple version command using ldflags on build and `runtime` package at runtime.
=> Fix #108: Add version command

pkg/cmd/create/root.go
We use K8s version 1.27 in tests, while the default version in CLI is set at 1.26. We should use 1.27 for all.
1.27.3 was taking from Kind release that we use: https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0
=> update default cluster version to 1.27

hack/ingress-nginx/cm-ingress-nginx-controller.yaml, hack/ingress-nginx/kustomization.yaml, pkg/controllers/localbuild/resources/nginx/k8s/ingress-nginx.yaml
I was helping @csantanapr with running idpbuilder. Apparently on some systems, it is possible for ingress-nginx's default buffer size to be too small (4k) for header values. 
Error message looks something like: 
```
upstream sent too big header while reading response header from upstream, client
```
Setting the value to 32k resolved the issue. I think we should just set the value to 32k so this doesn't happen.
=> set ingress-nginx buffer size to 32k

examples/local-backup/kind.yaml, examples/ref-implementation/README.md, examples/ref-implementation/replace-port.sh, hack/ingress-nginx/deployment-ingress-nginx.yaml, hack/ingress-nginx/service-ingress-nginx.yaml, pkg/build/build.go, pkg/cmd/create/root.go, pkg/controllers/crd.go, pkg/controllers/custompackage/controller.go, pkg/controllers/gitrepository/controller.go, pkg/controllers/localbuild/argo.go, pkg/controllers/localbuild/argo_test.go, pkg/controllers/localbuild/controller.go, pkg/controllers/localbuild/gitea.go, pkg/controllers/localbuild/installer.go, pkg/controllers/localbuild/nginx.go, pkg/controllers/localbuild/resources/gitea/k8s/install.yaml, pkg/controllers/localbuild/resources/gitea/values.yaml, pkg/controllers/localbuild/resources/nginx/k8s/ingress-nginx.yaml, pkg/controllers/run.go, pkg/kind/cluster.go, pkg/kind/cluster_test.go, pkg/kind/resources/kind.yaml, pkg/util/build_config.go, pkg/util/files.go, pkg/util/fs.go
- add a --port flag to configure the default port
- add go templates directives to override embedded resource manifests
- template kind cluster config
- add a sample script to tweak the port for the reference example
closes #139
=> make the serving port for idpBuilder configurable

pkg/controllers/localbuild/controller.go
There is a situation where the CLI never shuts down when a previously installed custom packages are not specified in subsequent commands. For example:
1. Run: `idpbuilder create --package-dir examples/basic/package1`. 
2. Run: `idpbuilder create --package-dir examples/basic/package2`. This never exits.
3. If you do `./idpbuilder create --package-dir examples/basic/package2 --package-dir examples/basic/package1`, it shuts down as expected.
This is because the annotation value we use to track CLI invocation time is updated for specified packages only. So when you run the second command, the annotations for the packages in `examples/basic/package2` are updated but not for the existing packages in the first package. When we check if we need to shutdown, we look at all package objects in the …
=> ignore unspecified packaegs when shutting down

pkg/build/build.go, pkg/cmd/create/root.go, pkg/cmd/helpers/logger.go, pkg/cmd/root.go
As mentioned in #15, currently it's not possible to configure logging format or level.
This PR ensures logging customization work and implements our own defaults: RFC3339 timestamps and console logs.
Uses slog as the underlying implementation.
=> allow for logging customization

pkg/build/build.go, pkg/cmd/helpers/logger.go, pkg/controllers/crd.go, pkg/controllers/custompackage/controller.go, pkg/controllers/custompackage/controller_test.go, pkg/controllers/gitrepository/controller.go, pkg/controllers/localbuild/controller.go, pkg/controllers/localbuild/installer.go, pkg/controllers/run.go
Setting some messages to be logged at debug level instead of all being at info level. I don't think they are useful for end users unless they run into a problem.
=> reduce log messages

pkg/kind/cluster.go
When asking KinD for a provider, use the detection option instead of forcing it to the Docker provider.
This allows the new capability in KinD to use nerdctl or finch to work properly with idpbuilder.
=> Allow other KinD providers to work

examples/ref-implementation/keycloak/manifests/secret-gen.yaml
add labels to expose ref-implementation credentials when calling `get secrets`
=> add labels to expose keycloak secrets

examples/ref-implementation/keycloak/manifests/keycloak-config.yaml
With the ArgoCD upgrade, I guess the token endpoint needs content type specified.
=> ref-impl: specify content type

examples/local-backup/kind.yaml, pkg/kind/cluster_test.go, pkg/kind/resources/kind.yaml.tmpl
=> Do not allocate memory for system in kind

examples/ref-implementation/backstage-templates/entities/basic/skeleton/manifests/deployment.yaml
When deploying the reference implementation and then creating a Backstage component from the `basic` template, the Kubernetes tab would only show the deployment, but no pod information due to the missing `entity-id` label on the deployment's `spec.template.metadata` object.
=> Fix Backstage labels for basic backstage template

examples/terraform-integrations/README.md, examples/terraform-integrations/terraform-workflows-templates.yaml
creates a new example runner for launching terraform templates from within the idpBuilder
=> adds the argo workflow to run terraform templates

examples/terraform-integrations/README.md
Updating `ReadMe` documentation for Backstage Terraform Integrations to support package integrations with [Backstage Terraform Integrations](https://github.com/cnoe-io/backstage-terraform-integrations/tree/main) repo.
=> Updating `ReadMe` documentation for Backstage Terraform Integrations

README.md
- Include a prerequisites section covering the container engines. 
- Add a warning and note about podman usage
- See: #214
=> Improve doc: container engine

CONTRIBUTING.md, examples/ref-implementation/backstage/manifests/install.yaml, hack/gitea/values.yaml, pkg/cmd/get/secrets.go, pkg/cmd/get/secrets_test.go, pkg/controllers/localbuild/gitea.go, pkg/controllers/localbuild/resources/gitea/k8s/install.yaml
partially fixes #216
This only covers the gitea secret renaming, as apparently the argocd one is generated by argo on installation, and is hardcoded to `argocd-initial-admin-secret`.
See here: https://github.com/argoproj/argo-cd/blob/0f11dfb5961361807962aafc68b11426b8a47490/cmd/argocd/commands/admin/initial_password.go#L16
There's some world where we could replicate the secret into one with a name we like better, but that sounds like a recipe for confusion.
=> fix: rename gitea secret for better description

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature.yaml
=> add feature GH template

pkg/cmd/get/secrets.go, pkg/cmd/get/secrets_test.go
Adds argocd admin username to the get secrets command as mentioned in https://github.com/cnoe-io/idpbuilder/issues/216
```
./idpbuilder get secrets -p argocd
---------------------------
Name: argocd-initial-admin-secret
Namespace: argocd
Data:
password : abc
username : admin
```
=> add argocd admin username

pkg/cmd/get/root.go, pkg/cmd/get/secrets.go, pkg/cmd/get/secrets_test.go
This adds json and yaml output options to the get command. I need this functionality for e2e tests I am trying to add because I need to be able to parse command outputs programmatically. 
```bash
./idpbuilder get secrets -o json
[
{
"name": "argocd-initial-admin-secret",
"namespace": "argocd",
"data": {
"password": "abc",
"username": "admin"
}
},
{
"name": "gitea-credential",
"namespace": "gitea",
"data": {
"password": "abc",
"username": "giteaAdmin"
}
}
]
```
=> add json and yaml output format

Makefile, hack/embedded-resources.sh
=> feat:add embedded-resources target in Makefile

.github/workflows/e2e.yaml, Makefile, tests/e2e/docker/docker_test.go, tests/e2e/e2e.go
This adds initial e2e tests for core packages only.
We are mainly testing rest API responses so we have flexibility in testing tools to use. 
- They are easier and less verbose to write. Probably easier for people not familiar with Go to contribute too.
- Rich selection of tools from mature ecosystems.
I think this is one of common approaches. What I do not like about this is the mental overhead when switching to another language. I'm not too good at switching from one language to another when writing things. 
Bringing another language means we are bloating the requirements to work on this project. In addition to installing language runtime, we will need to introduce setup scripts and guides for the chosen language. For example, installing the right version of python then setting up venv. …
=> add initial e2e tests

hack/argo-cd/argocd-application-controller.yaml, hack/argo-cd/argocd-applicationset-controller.yaml, hack/argo-cd/argocd-redis.yaml, hack/argo-cd/argocd-repo-server.yaml, hack/argo-cd/argocd-server.yaml, hack/argo-cd/dex-server.yaml, hack/argo-cd/kustomization.yaml, hack/argo-cd/notifications-controller.yaml, hack/gitea/generate-manifests.sh, hack/gitea/values.yaml, pkg/controllers/localbuild/resources/argo/install.yaml, pkg/controllers/localbuild/resources/gitea/k8s/install.yaml
=> Fix pull policy

examples/terraform-integrations/README.md
Documentation update to FluxCD and ToFu Controller to Terraform Integration ReadMe documentation to stay intact.
=> Documentation Update for FluxCD and ToFu Controller

README.md, examples/terraform-integrations/README.md
This PR is to fix Typos and Versions with stale information in ReadMe.
=> Fixing Typos and Versions

examples/terraform-integrations/tofu-controller.yaml
Fixes `The ConfigMap is invalid: metadata.annotations: Too long` issue when installing the tf-controller.
Also bumps the version of the tofu controller
The problem is discussed in details here: https://github.com/argoproj/argo-cd/issues/820 and the issue suggests to use `ServerSideApply=true` to skip the use of Kubectl when applying resources.
/cc @elamaran11
=> enable serverside apply for tf-controller install

examples/localstack-integration/README.md, examples/localstack-integration/crossplane-provider-localstack.yaml, examples/localstack-integration/crossplane-provider-localstack/provider-config-localstack.yaml, examples/localstack-integration/localstack.yaml
This adds localstack as an addon to the ref implemention, which involves the following:
Install localstack as argo application
Add a new Crossplane ProviderConfig for localstack
I already attempted to add the same directly to the ref impl [here](https://github.com/cnoe-io/idpbuilder/pull/248), but there were lots of cross-cutting concerns there. This is more of a drop-in, although doesn't integrate quite as much.
I think this should be much more acceptable, despite the minor UX downsides.
=> Add localstack as addon package

README.md, pkg/cmd/create/root.go
This pull request corrects the URLs for accessing the ArgoCD and Gitea UIs specified in the README. The previous URLs did not correctly reflect the actual URLs for accessing these services.
- The URL for ArgoCD has been updated from 'https://cnoe.localtest.me:8443/argocd/' to 'https://argocd.cnoe.localtest.me:8443/'
- The URL for Gitea has been updated from 'https://cnoe.localtest.me:8443/gitea/' to 'https://gitea.cnoe.localtest.me:8443/'
These changes ensure that users are directed to the correct locations when setting up their local development environment.
=> Fix Incorrect ArgoCD and Gitea UI URLs in README.md

README.md, hack/install.sh
=> add pipe to bash script

pkg/util/util.go
When using idpbuilder with bash, the gitea secret could contain special characters that are not user or bash friendly.  Especially in bash scripts, special characters often have meaning. Removing the following characters: `"`, `\`.
Ref: https://cloud-native.slack.com/archives/C05TN9WFN5S/p1717410133645919
=> remove problematic special chars for bash

hack/gitea/generate-manifests.sh, hack/gitea/values.yaml, pkg/controllers/localbuild/resources/gitea/k8s/install.yaml, pkg/kind/cluster_test.go, pkg/kind/resources/kind.yaml.tmpl
This is now working with the following patch for gitea: https://github.com/jessesanford/gitea/blob/c2fffabcd5122d258360d4443b6e583fc62e28f1/routers/api/packages/container/container.go#L119-L131
We need to decide if we want to use this forked version temporarily while we shape a PR for upstream or continue to use an additional registry. @nimakaviani @nabuskey @greghaynes wdyt?
=> Enable gitea oci registry

pkg/cmd/get/secrets.go
As mentioned by @cmoulliard in #283 , the get secret json output escapes certain special characters. This behaviour is not desirable for our purposes.
https://pkg.go.dev/encoding/json#Encoder.SetEscapeHTML
=> remove html escape

pkg/controllers/localbuild/controller.go, pkg/controllers/localbuild/gitea.go, pkg/controllers/localbuild/installer.go
Currently, we install core packages sequentially and some of them take minimum one minute to install. We can install them in parallel to significantly reduce bootstrap time. 
Current:
```bash
real	2m53.446s
user	0m1.647s
sys	0m0.934s
```
With this PR:
```bash
real	1m27.973s
user	0m1.729s
sys	0m0.919s
```
The absolute amount in reduction varies between systems, but it should reduce the time to bootstrap by a similar percentage.
=> parallel install core

pkg/controllers/localbuild/controller.go, pkg/util/git_repository.go, pkg/util/util.go
We should be looking at yaml files only when processing custom packages.
=> ensure only yaml files are processed

go.mod, go.sum
``` 
~/code/idpbuilder-omri │ update-deps *1 !3  grype dir:. --exclude './bin/**' -o json                                                                                                                    
✔ Vulnerability DB                [no update available]  
✔ Indexed file system                                                                                                                                                                                                          .
✔ Cataloged contents                                                                                                                                            cdb4ee2aea69cc6a83331bbe96dc2caa9a299d21329efb0336fc02a82e1839a8
├── ✔ Packages                        [124 packages]  
└── ✔ Executables …
```
=> update docker dependency version to address CVE

examples/ref-implementation/keycloak/manifests/keycloak-config.yaml
In preparation for adding the observability stack, Grafana requires an email address for SSO users.
=> add email addresses to users in keycloak

README.md, docs/pluggable-packages.md, pkg/cmd/create/root.go, tests/e2e/docker/docker_test.go
Solves: https://github.com/cnoe-io/idpbuilder/issues/264
One thing I didn't know if we wanted to do it in this PR is to setup the skeleton for supporting non-local packages like noted in this comment: https://github.com/cnoe-io/idpbuilder/issues/264#issuecomment-2136865214 I thought that fell out of the scope of the ask in the issue but I am happy to establish that start if it is better to do it in this PR.
=> Add Package Flag and Mark Package-Dir as Deprecated

pkg/build/build.go, pkg/build/coredns.go, pkg/build/templates/coredns/cm-coredns-custom.yaml, pkg/build/templates/coredns/cm-coredns-default.yaml.tmpl, pkg/build/templates/coredns/cm-coredns.yaml, pkg/build/templates/coredns/deployment-coredns.yaml, pkg/cmd/create/root.go
fixes: #300 
This allows for in-cluster hostname resolutions using CoreDNS.
From a pod in the cluster:
```
root@debug-pod:/# dig cnoe.localtest.me +short
10.96.30.155
root@debug-pod:/# dig abc.cnoe.localtest.me +short
10.96.30.155
```
A few points about CoreDNS I should make clear:
1. CoreDNS file allows you to import files matching a pattern.
2. By default, CoreDNS installation only mounts the corefile key within coredns CM.
Taken together, what we need to do to allow our default customization and possible further customization:
1. Update the coredns CM to use the import plugin, then make it look for files matching `/etc/coredns-configs/*.conf`
2. Populate `/etc/coredns-configs/` with two files (sourced from CMs):
- One that contains our default configuration. That is to resolve the name …
=> configure core dns for internal name resolution

globals/project.go, hack/argo-cd/argocd-tls-certs-cm.yaml.tmpl, hack/argo-cd/kustomization.yaml, hack/ingress-nginx/deployment-ingress-nginx.yaml, pkg/build/build.go, pkg/build/tls.go, pkg/build/tls_test.go, pkg/cmd/create/root.go, pkg/controllers/gitrepository/controller_test.go, pkg/controllers/localbuild/controller.go, pkg/controllers/localbuild/installer.go, pkg/controllers/localbuild/nginx.go, pkg/controllers/localbuild/resources/argo/install.yaml, pkg/controllers/localbuild/resources/nginx/k8s/ingress-nginx.yaml, pkg/k8s/client.go, pkg/k8s/deserialize.go, pkg/util/build_config.go, pkg/util/files.go
fixes: #137 
related to: #300 #293
With this PR, idpbuilder will:
1. Create a self signed certificate.
2. Create a TLS secret in the ingress-nginx NS.
3. Use it as the default TLS certificate for ingress-nginx. (you can still use other certs configured at ingress level)
4. Update ArgoCD's CM to trust the CA.
5. Create a CM that contains cert to the default NS.
I thought about using cert-manager but decided not to use it. For our purposes, we just need a certificate for ingress-nginx for in-cluster and incoming traffic only. Introducing cert-manager means:
1. We need to maintain cert-manager manifests.
2. Slower installation speed. We now need to wait for cert-manager to do its thing and be ready before anything else can continue.
3. Introduces three pods that will do nothing for the most …
=> issue self signed certificate 

.github/workflows/e2e.yaml, .github/workflows/pr.yaml, .github/workflows/release.yaml
checkout-go v4 is close to being deprecated because node16 is deprecated in GH.
=> update gh actions versions

pkg/controllers/localbuild/gitea.go, pkg/controllers/localbuild/gitea_test.go
Currently argocd applications are synced to gitea repositories by using the internal service URLs like `http://my-gitea-http.gitea.svc.cluster.local:3000`. This PR changes the behaviour to use the now internally resolvable URL instead. Users can now use the URL given in the Gitea UI to configure ArgoCD.
=> use internally and externally resolvable git url

.github/workflows/nightly.yaml, .github/workflows/release.yaml
Addresses #281 
Note: we need to create a repo secret called `GH_NIGHTLY_TOKEN` that has permissions to commit to `idpbuilder` and publish packages. This is a GH limitation: https://github.com/orgs/community/discussions/27028#discussioncomment-3254360
At 12 AM PST, a workflow will run that takes the latest main and pushes it as a new nightly tag. It will then delete the last nightly release. The creation of the new tag will trigger the release workflow to run which will create a new release off the nightly tag. 
I also had to `go fmt` the `root.go` file or the release will fail.
=> Adding nightly builds to idpbuilder

README.md, hack/install.sh
Right now, the install script and the install instructions downloads the latest nightly release. This is not what we want. We want users to use the latest stable version. 
Currently:
```bash
version=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/cnoe-io/idpbuilder/releases/latest)
version=${version##*/}
echo $version
v0.6.0-nightly.20240705 
```
With this PR:
```bash
version=$(curl -s https://api.github.com/repos/cnoe-io/idpbuilder/releases | grep tag_name | grep -o -e '"v[0-9].[0-9].[0-9]"' | head -n1 | sed 's/"//g')
echo $version
v0.5.0
```
=> ensure latest stable version is downloaded

pkg/controllers/custompackage/controller.go, pkg/controllers/custompackage/controller_test.go, pkg/controllers/custompackage/test/resources/customPackages/applicationSet/generator-matrix.yaml
ApplicationSet has a generator called matrix generator: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/
This can embed other generators like the git generator. We need to support it for use cases where parameter values are pulled from git.
=> support matrix git generator

pkg/controllers/localbuild/argo_test.go, pkg/controllers/localbuild/controller.go, pkg/util/util.go
fixes: #134 
related to: #297 
With this, idpbuilder requests ArgoCD to refresh application source when existing.
=> refresh argocd apps on exit

pkg/kind/cluster.go, pkg/kind/cluster_test.go, pkg/kind/resources/kind.yaml.tmpl
fixes: #315
```
$ docker login gitea.127.0.0.1.nip.io:8443
Username: giteaadmin
Password:
WARNING! Your password will be stored unencrypted in /home/ubuntu/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
$ docker tag docker.io/library/ubuntu:24.04 gitea.127.0.0.1.nip.io:8443/giteaadmin/ubuntu:24.04
$ docker push gitea.127.0.0.1.nip.io:8443/giteaadmin/ubuntu:24.04
The push refers to repository [gitea.127.0.0.1.nip.io:8443/giteaadmin/ubuntu]
a30a5965a4f7: Pushed
24.04: digest: sha256:19bc204df71f4086020b609089ebf49b332c2e373ec31e3512644b8ad9615001 size: 529
```
=> use go template for gitea registry

go.mod, pkg/build/build.go, pkg/cmd/delete/root.go, pkg/cmd/get/clusters/clusters.go, pkg/cmd/get/root.go, pkg/cmd/list/root.go, pkg/cmd/root.go
This isnt perfect, but this should handle the 90% case for when users dont want to have to install kind separately.
=> Add delete and list command

tests/e2e/docker/docker_test.go, tests/e2e/e2e.go
In GH actions, due to limited compute resources availability, e2e tests tend to fail more often than not. This adds basic retry logic to e2e to make sure there's a better chance of completing e2e.
=> add basic retry for http requests

globals/project.go, pkg/build/tls.go, pkg/controllers/localbuild/argo.go, pkg/controllers/localbuild/argo_test.go, pkg/controllers/localbuild/controller.go
Currently ArgoCD does not use our cert. This PR changes that. This allows services that want to communicate with ArgoCD to do so without disabling TLS verification all together (still need to import the cert).
```
$ openssl s_client -showcerts -servername argocd.cnoe.localtest.me -connect argocd.cnoe.localtest.me:8443 </dev/null | openssl x509 -text | grep 'Subject Alternative Name' -A 1
X509v3 Subject Alternative Name:
DNS:cnoe.localtest.me, DNS:*.cnoe.localtest.me
```
=> use self-signed cert for argocd server

pkg/controllers/localbuild/argo_test.go, pkg/controllers/localbuild/controller.go
On exit, we currently refresh ALL ArgoCD Applications. If applications are owned by application sets, we should not refresh them ourselves. Let ApplicationSets refresh instead.
=> skip refresh if owned by app set

.github/workflows/e2e.yaml, .github/workflows/pr.yaml, .github/workflows/release.yaml, go.mod
**Description:**
This pull request addresses Issue #259 by updating the Go version from 1.21 to 1.22. The following changes have been made:
- Updated the Go version in `idpbuilder/go.mod` to 1.22.
- Modified `.github/workflows/e2e.yaml`, `.github/workflows/pr.yaml`, and `.github/workflows/release.yaml` to use Go version 1.22.
These changes are necessary to support the upgrade to Kubernetes 1.30, which requires Go 1.22.
=> Bump Go version to 1.22

hack/install.sh
On some ARM64 Linux instances, `uname -m` returns `aarch64` instead of `arm64`. This causes the installation script to fail.
This change adds an additional substitution for this scenario
=> Add substitution for aarch64 to installation bash script

pkg/kind/cluster.go, pkg/kind/cluster_test.go, pkg/kind/testdata/expected/necessary-port-present.yaml, pkg/kind/testdata/expected/no-necessary-port.yaml, pkg/kind/testdata/necessary-port-present.yaml, pkg/kind/testdata/no-necessary-port.yaml
fixes: #358, #366
With this we always insert the ingress port we need when a custom kind configuration is provided.
=> ensure ingress port is available

Makefile
This PR updates the controller-gen version in the `idpbuilder` module to align with the updated Kubernetes version.
- Updated the `CONTROLLER_TOOLS_VERSION` in the `Makefile` from `v0.14.0` to `v0.15.0`.
This PR addresses issue #364 and is related to the Kubernetes update mentioned in issue #260.
=> Updated controller tools version

hack/ingress-nginx/kustomization.yaml, pkg/controllers/localbuild/resources/nginx/k8s/ingress-nginx.yaml
This upgrades ingress-nginx version.
This also uses the kind specific manifest available from ingress-nginx.
=> upgrade ingress-nginx

pkg/controllers/resources/idpbuilder.cnoe.io_custompackages.yaml, pkg/controllers/resources/idpbuilder.cnoe.io_gitrepositories.yaml, pkg/controllers/resources/idpbuilder.cnoe.io_localbuilds.yaml
Looks like controller gen was updated but was not run in #369 and nightly release is failing.
=> run controller gen to update crds

pkg/cmd/helpers/logger.go, pkg/cmd/root.go, pkg/logger/handler.go
Currently, log outputs are hard to read. For example:
```
time=2024-08-26T20:22:19.468Z level=INFO msg="Creating kind cluster" logger=setup cluster=localdev
time=2024-08-26T20:22:36.409Z level=INFO msg="Done creating cluster" logger=setup cluster=localdev
time=2024-08-26T20:22:36.566Z level=INFO msg="Adding CRDs to the cluster" logger=setup
time=2024-08-26T20:22:37.377Z level=INFO msg="Setting up CoreDNS" logger=setup
time=2024-08-26T20:22:37.404Z level=INFO msg="Setting up TLS certificate" logger=setup
time=2024-08-26T20:22:37.425Z level=INFO msg="Creating localbuild resource" logger=setup
time=2024-08-26T20:22:37.425Z level=INFO msg="Starting EventSource" controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild source="kind source: *v1alpha1.Localbuild"
``` …
=> Change logging format

pkg/cmd/create/root.go
=> update default k8s version to v1.30

hack/gitea/ingress.yaml.tmpl, pkg/controllers/localbuild/resources/gitea/k8s/install.yaml
Fixes #327 by setting up nginx rewrite rules on the ingress so that the generic OCI registry discovery urls can be found when using path based routing.
=> Fixes #327: OCI Registry for use with path-based-routing

hack/gitea/values.yaml, pkg/controllers/localbuild/resources/gitea/k8s/install.yaml
Gitea webhook event POST call is failing with `webhook can only call allowed HTTP servers (check your webhook.ALLOWED_HOST_LIST setting)`, fixing this issue by adding webhook settings to allow private IPs and Skip TLS Verify.
=> Added config for gitea to support webhooks trigger

pkg/controllers/localbuild/resources/gitea/k8s/install.yaml
Looks like the generate manifest command was missed in the previous PR. We really need #372 to catch these things in PR builds. This caused the nightly build to fail: https://github.com/cnoe-io/idpbuilder/actions/runs/10898267574
=> run generate command

.github/workflows/pr.yaml
We need the PR build to fail if git is in dirty state to ensure generated files are actually generated, not written manually.
fixes: #398
=> fail pr action if git is in ditry state

pkg/build/templates/coredns/cm-coredns-default.yaml.tmpl
- Add the missing parameters `answer auto` to the rewrite rule to let `coreDNS` to generate the answer response
- Why : to avoid a man in the middle DNS attack, to avoid that some CLI running part of a fedora image raise a Host not found while curl, ping, work
- See: #398
=> Add the missing parameters: answer auto

README.md
Lets remove the WIP notice at the top of the readme, we're at a high enough level of maturity this is likely causing more harm than good.
Also adding some commands to make it extremely simple for a new user to get up and running.
=> Update readme, removing WIP and adding install info

pkg/kind/cluster_test.go, pkg/kind/resources/kind.yaml.tmpl, tests/e2e/docker/docker_test.go, tests/e2e/docker/test-dockerfile, tests/e2e/e2e.go
=> fix gitea registry for path based routing

.devcontainer/postCreateCommand.sh
Docker was updated in Codespaces and it caused an issue with Kind. This is a workaround for it. It just pre-creates the kind network.
For a more permanent fix, we need to update Kind once a new version with the fix is released.
https://github.com/cnoe-io/idpbuilder/issues/412
fixes: https://github.com/cnoe-io/idpbuilder/issues/386
=> Workaround for codespaces

pkg/controllers/localbuild/gitea.go, pkg/controllers/localbuild/gitea_test.go
Related to: #425 
This fixes the nil reference when the gitea client initialization errors out due to a timeout. A timeout can be caused by resource contentions.
=> use gitea NewClient to catch errors

tests/e2e/e2e.go
This adds retry logic to give it more time to retrieve credentials in E2E like here: https://github.com/cnoe-io/idpbuilder/actions/runs/11622415016/job/32368940613
=> add retry for getting credentials

pkg/build/build.go, pkg/kind/cluster.go, pkg/kind/cluster_test.go, pkg/kind/kindlogger.go
Currently, when kind cluster creation fails, the only feedback users get is the status code. It's really not useful for end users and it's very difficult to troubleshoot cluster creation problems.
This PR ensures we log kind errors.
Current:
```
Nov  5 16:14:44 INFO Creating kind cluster logger=setup cluster=my-konflux
Nov  5 16:14:45 ERROR Error starting kind cluster logger=setup err=command "podman run --name my-konflux-control-plane --hostname my-konflux-control-plane --label io.x-k8s.kind.role=control-plane --privileged --tmpfs /tmp --tmpfs /run --volume 3b99d6c3e2675118c358c91abcd4a44c0734c822a60fd0c7b504ad916ef036b7:/var:suid,exec,dev --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --net kind --label io.x-k8s.kind.cluster=my-konflux …
```
=> ensure kind command outputs are available

pkg/cmd/create/root.go
Moved flag descriptions to consts. Updated descriptions to be more descriptive.
=> clarify create command flags

pkg/cmd/create/root.go
This prints the correct URL when idpbuilder is used in Codespaces. We do promote the use of Codespaces to get going quickly so I think it's a good idea to have something small like this to make the experience better. 
If you are using another proxy like Caddy instead, this prints out the URL correctly as well. You just need to set `CODESPACES=true` when running idpbuilder. 
fixes: #269
fixes: #452
=> print url for codespaces

pkg/cmd/create/root.go, pkg/cmd/delete/root.go, pkg/cmd/get/clusters.go, pkg/cmd/get/secrets.go
Set `SilenceUsage: true,` for commands to prevent usages from being printed every time an error occurs.
before:
```
idpbuilder get secrets
Error: getting kube config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
Usage:
idpbuilder get secrets [flags]
Flags:
-h, --help   help for secrets
Global Flags:
--color              Enable colored log messages.
-l, --log-level string   Set the log verbosity. Supported values are: debug, info, warn, and error. (default "info")
-o, --output string      Output format. json or yaml.
-p, --packages strings   names of packages.
getting kube config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
After:
```
idpbuilder get secrets …
```
=> prevent printing usages on error

.goreleaser.yaml
=> Updates goreleaser.yaml to mark nightly builds as pre-release

api/v1alpha1/localbuild_types.go, pkg/controllers/custompackage/controller.go, pkg/controllers/custompackage/controller_test.go, pkg/controllers/localbuild/controller.go, pkg/util/util.go, pkg/util/util_test.go
This adds `cnoe.io/package-name` and `cnoe.io/package-type` labels to applications. Then use the label to wait for core packages to be healthy.
=> add labels to applications

.github/workflows/e2e.yaml, .github/workflows/slash-commands.yaml
This allows for people with `write` permissions to this repository to run the e2e workflow by commenting `/e2e` in PRs.
Tested here:  https://github.com/nabuskey/idpbuilder/pull/1
fixes: https://github.com/cnoe-io/idpbuilder/issues/254
=> allow /e2e in PRs to run e2e workflow

go.mod, go.sum, pkg/cmd/get/clusters.go, pkg/cmd/get/root.go, pkg/cmd/helpers/k8s.go, pkg/cmd/root.go
- Improve the cmd: get clusters to show the cluster, nodes and their internal IP. 
- Created a help function to access globally to the kube client. 
- Add a new parameter to set the kubeconfig path
```
./idpbuilder -h
Manage reference IDPs
Usage:
idpbuilder [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
create      (Re)Create an IDP cluster
delete      Delete an IDP cluster
get         get information from the cluster
help        Help about any command
version     Print idpbuilder version and environment info
Flags:
--color              Enable colored log messages.
-h, --help               help for idpbuilder
--kubePath string    kube config file Path.
```
- Command currently shows:
```
Cluster: my-konflux
URL of the kube API server: …
```
=> Improve the cmd: get clusters

main.go, pkg/build/build.go, pkg/cmd/create/root.go, pkg/cmd/get/secrets.go, pkg/cmd/root.go, pkg/controllers/run.go
This PR makes idpbuilder handle interrupts correctly. Currently, idpbuilder doesn't handle signals well. For example, if you send ctrl+c while it's executing, it prints out a message saying `Finished Creating IDP Successfully!`. With this PR, it correctly says that the command execution was interrupted. It still prints command usages at the end but we can address that in another PR.
=> handle command interrupt

api/v1alpha1/gitrepository_types.go, api/v1alpha1/localbuild_types.go, hack/argo-cd/argocd-cm.yaml, hack/argo-cd/argocd-rbac-dev.yaml, hack/argo-cd/kustomization.yaml, pkg/build/build.go, pkg/cmd/create/root.go, pkg/cmd/get/secrets.go, pkg/controllers/gitrepository/controller.go, pkg/controllers/gitrepository/gitea.go, pkg/controllers/localbuild/argo.go, pkg/controllers/localbuild/argo_test.go, pkg/controllers/localbuild/controller.go, pkg/controllers/localbuild/gitea.go, pkg/controllers/localbuild/gitea_test.go, pkg/controllers/localbuild/resources/argo/install.yaml, pkg/controllers/resources/idpbuilder.cnoe.io_localbuilds.yaml, pkg/k8s/util.go, pkg/util/argocd.go, pkg/util/gitea.go, pkg/util/secret.go, pkg/util/util.go
- Add new parameter to enable/disable: dev mode
- Set the default password for gitea 
- #441
=> Create default passwords when dev mode is set. #441

tests/e2e/e2e.go
- Fix wrong import and replace entity with types from printer to fix e2e tests failing
=> Fix wrong import and replace entity with types from printer

.devcontainer/postCreateCommand.sh, go.mod, go.sum, pkg/cmd/create/root.go
0.25.0 contains a fix for running kind in codespaces without introducing many breaking changes.
The only breaking changes between 0.23.0 and 0.25.0 are changes to the default k8s node image ([1.30.0 -> 1.31.2](https://github.com/kubernetes-sigs/kind/releases)). We could upgrade to 0.26.0 but it's not necessary for the fix mentioned in https://github.com/cnoe-io/idpbuilder/issues/420 .
Fixes https://github.com/cnoe-io/idpbuilder/issues/420
=> upgrade kind from 0.23.0 to 0.25.0

hack/gitea/values.yaml, pkg/controllers/localbuild/resources/gitea/k8s/install.yaml, pkg/kind/cluster_test.go, pkg/kind/resources/kind.yaml.tmpl
Sets up gitea ssh to be exposed at 32222 on the host network, container, and service layers.
It's unclear to me if we always want to expose this port. If we decide the host port we can ensure the gitea `SSH_PORT` setting matches which makes the ssh clone URL in gitea work.
fixes https://github.com/cnoe-io/idpbuilder/issues/227
=> Expose the gitea ssh port on 32222

.github/workflows/release.yaml
For homebrew-tap token create-token GH action requires repository to be specified otherwise it will create token only for the current repository. 
Ref: https://github.com/actions/create-github-app-token?tab=readme-ov-file#repositories
fixes: #479
=> fix: failing release job

.goreleaser.yaml
Changes goreleaser for marking nightly releases as prerelease.
Ref: https://goreleaser.com/customization/release/#github
=> fix: mark nightly release as prerelease

pkg/build/build.go, pkg/cmd/create/root.go, pkg/kind/cluster.go, pkg/kind/cluster_test.go, pkg/kind/resources/kind.yaml.tmpl
The new registry-config option when used alone looks up the default
podman and docker registry config files and mounts them in the kind
container if they exist. Optionally a user can pass a specific file to
the flag to specify a custom path to mount as the registry config.
=> Add registry-config option

pkg/kind/cluster.go, pkg/kind/config.go, pkg/kind/config_test.go, pkg/kind/testdata/custom-kind.yaml.tmpl
refactors pkg/kind/cluster.go into pkg/kind/config.go in order to simplify testing and adds relevant tests for the new utility functions. Also cleans up some unnecessary code in pkg/kind/cluster_test.go
=> refactor pkg/kind

hack/argo-cd/ingress.yaml.tmpl, hack/gitea/ingress.yaml.tmpl, pkg/build/tls.go, pkg/controllers/localbuild/gitea.go, pkg/controllers/localbuild/resources/argo/ingress.yaml, pkg/controllers/localbuild/resources/gitea/k8s/install.yaml, pkg/util/argocd.go, pkg/util/gitea.go
This PR fixes a few bugs around using the `--ingress-host-name` flag, `--dev-password` flag, and `--use-path-routing` flag. I initially wanted to separate these but decided they make sense to keep together since they're all a little bit interdependent.
Before this change using the `--ingress-host-name` flag would cause argo to fail to fetch repos from gitea due to missing SANs in the TLS cert. It also fixes a bug where we're hardcoding the domain for argocd and gitea to `cnoe.localtest.me` in the `--dev-password` codepath.
=> fix bugs around ingress, tls, and dev-password

pkg/controllers/localbuild/controller.go
Every time we change the admin password in argocd it clears the active user sessions. This makes iteration with developing stacks a bit tedious as you end up running `idpbuilder --dev-password -p stackname` a lot and you have to log back into argo every time. This is a minor inconvenience but I don't see any reason we can't fix it.
=> don't set the admin password repeatedly when using --dev-password

pkg/cmd/get/clusters.go, pkg/cmd/get/packages.go, pkg/cmd/get/root.go, pkg/cmd/get/secrets.go, pkg/k8s/client.go, pkg/util/argocd.go, pkg/util/gitea.go, pkg/util/idp.go, pkg/util/k8s.go
This centralizes the GetKubeClient and GetKubeConfig functions so that we're always using the right kube config path
=> fix bugs around kube config path flags

.goreleaser.yaml, README.md
Configure goreleaser not to publish formula `idpbuilder.rb` if the build is nigtly. For nightly. build, it should only update formula in `idpbuilder-nightly.rb`. This way following instruction for installing idpbuilder would work as intended.
+ Stable Version
```bash
brew install cnoe-io/tap/idpbuilder
```
+ Specific Stable Version
```bash
brew install cnoe-io/tap/idpbuilder@<version>
```
+ Nightly Version
```bash
brew install cnoe-io/tap/idpbuilder-nightly
```
=> Disable formula upload of idpbuilder.rb for nightly builds
