README.md

Changed the command in the quickstart to `./idpbuilder create --buildName localdev`
Fixes #40

Fix Quickstart > Run command

---

pkg/controllers/gitserver/controller_test.go

fixes: #37 
Built-in controllers don't run so we can just look at objects instead of waiting for a deployment to be ready.

fix git controller test

---

pkg/controllers/localbuild/resources/gitea/k8s/install.yaml
pkg/controllers/localbuild/resources/gitea/values.yaml

generated with 
```bash
helm template  my-gitea gitea-charts/gitea --version 9.5.1  -f pkg/controllers/localbuild/resources/gitea/values.yaml > pkg/controllers/localbuild/resources/gitea/k8s/install.yaml && echo "---
apiVersion: v1
kind: Secret
metadata:
name: gitea-admin-secret
type: Opaque
stringData:
username: giteaAdmin
password: giteaPassword\n" >> pkg/controllers/localbuild/resources/gitea/k8s/install.yaml 
```

correct endpoints and use correct api version

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
go.mod

This gets us using GoLang 1.21 which is the latest stable version of GoLang.

Update to GoLang 1.21

---

go.mod
go.sum
pkg/docker/container.go
pkg/kind/cluster.go
pkg/kind/cluster_test.go

fail if the idpBuilder is launched on a different port

---

examples/ref-implementation/crossplane-compositions/manifests/s3/general-purpose.yaml

add one default tag to avoid issues with Ready status

---

hack/gitea/generate-manifests.sh
hack/gitea/gitea-creds.yaml
pkg/controllers/localbuild/gitea.go
pkg/controllers/localbuild/installer.go
pkg/controllers/localbuild/resources/gitea/k8s/install.yaml
pkg/util/util.go
pkg/util/util_test.go

fixes: #192 
Note that this does not in no way makes our gitea installation secure. This is just a bare minimum. You still need to configure Gitea if you want to make it accessible from outside.

generate gitea password

---

examples/ref-implementation/README.md
examples/ref-implementation/external-secrets/generate-manifests.sh
examples/ref-implementation/external-secrets/manifests/install.yaml

Fix ESO namespace. Update the documentation to use the idpbuilder get command.

fix eso ns 

---

.devcontainer/devcontainer.json
.devcontainer/postCreateCommand.sh

add bash-completion for devcontainer

---

examples/ref-implementation/metric-server.yaml

Add metric-server to ref-implementation

---

examples/ref-implementation/keycloak/manifests/keycloak-config.yaml

This PR is a bug fix on `KEYCLOAK_URL` in KeyCloak Config.

Bug Fix on `KEYCLOAK_URL` Typo.

---

pkg/controllers/gitrepository/controller.go
pkg/controllers/gitrepository/gitea.go

we fixed it for the gitCliet in #206 but same can occur with the gitea client and this PR fixes it

fix gitea client timeout

---

.goreleaser.yaml

chore: add ldflags reduce binary size

---

hack/argo-cd/argocd-cm.yaml
pkg/controllers/localbuild/resources/argo/install.yaml

feat: Make argocd refresh faster, set from 3min to 1min

---

.github/workflows/nightly.yaml

This will clean up the previous nightly tag

remove last nightly tag

---

pkg/build/tls_test.go
pkg/controllers/localbuild/argo_test.go

I was using the wrong assert library.

use right assert

---

pkg/kind/cluster_test.go
pkg/kind/resources/kind.yaml.tmpl

use kind labels field

---

pkg/cmd/create/root.go
pkg/kind/cluster.go

Fixes https://github.com/cnoe-io/idpbuilder/issues/454

add support for http and https kind-configs

---

.goreleaser.yaml

fix: homebrew formula folder name

---

CONTRIBUTING.md

- Describe the process to bump the version of a core component for the CONTRIBUTORS 
- Ticket: #498

Describe the process to bump the version of a core component

---

docs/minimum-requirements.md
docs/private-registries.md

Addresses #444 and #393
Not sure if this is what we had in mind for the docs, if these should be moved elsewhere let me know

Add minimum requirements and private registry docs

---

hack/gitea/values.yaml
pkg/controllers/localbuild/resources/gitea/k8s/install.yaml

-  Generate a NodePort service for the gitea http. 
- See: #510

Generate a NodePort service for the gitea http.

---

Makefile

Adds support for platforms that report aarch64
Fixes #521
make build
make test

Support aarch64 platforms

---

.goreleaser.yaml
README.md

Fix goreleaser config to allow versioned installation and instructions
